spring.application.name=employee-management-system
spring.datasource.url=jdbc:postgresql://localhost:5432/ems_db
spring.datasource.username=postgres
spring.datasource.password=Sthiti

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt-secret=your-super-long-and-secure-random-secret-key-that-is-at-least-32-chars
app.jwt-expiration-milliseconds=604800000

server.port=8081